services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:3
    container_name: tsdproxy
    hostname: tsdproxy
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=America/Los_Angeles
    labels:
      tsdproxy.enable: true
      tsdproxy.name: dash
      tsdproxy.port.1: "443/https:8080/http" # dashboard
