# https://jellyfin.org/docs/general/installation/container/

services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: jellyfin/jellyfin:latest
    restart: on-failure

    user: 1000:1000

    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
      - 7359:7359/udp
      - 1900:1900/udp

    networks:
      - caddy
    labels:
      caddy: jellyfin.pibox.lan
      caddy.reverse_proxy: "{{upstreams https 8920}}"
      caddy.tls: internal

    volumes:
      - ./config:/config
      - ./cache:/cache
      - /data/media:/media:ro

    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
