services:
  docktail:
    image: ghcr.io/marvinvr/docktail:latest
    container_name: docktail
    hostname: docktail
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/tailscale:/var/run/tailscale
    environment:
      - DOCKTAIL_LOG_LEVEL=warn
      - DOCKTAIL_CHECK_INTERVAL=60s
      - TAILSCALE_OAUTH_CLIENT_ID=${TAILSCALE_OAUTH_CLIENT_ID}
      - TAILSCALE_OAUTH_CLIENT_SECRET=${TAILSCALE_OAUTH_CLIENT_SECRET}
