version: 5

mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1883

serial:
  port: /dev/ttyUSB0
  adapter: zstack
  baudrate: 115200
  rtscts: false

advanced:
  log_level: info
  channel: 11
  network_key:
    - 168
    - 86
    - 174
    - 27
    - 62
    - 243
    - 166
    - 221
    - 196
    - 101
    - 244
    - 65
    - 126
    - 67
    - 111
    - 89
  pan_id: 59834
  ext_pan_id:
    - 133
    - 231
    - 63
    - 172
    - 147
    - 128
    - 131
    - 153

frontend:
  enabled: true
  port: 8080

homeassistant:
  enabled: false

devices:
  "0x00124b0029e86f1a":
    friendly_name: Blue Light
  "0x00124b0029e858b5":
    friendly_name: Lamp
