# https://github.com/aceberg/WatchYourLAN
services:
  watchyourlan:
    image: aceberg/watchyourlan
    hostname: watchyourlan
    container_name: watchyourlan
    restart: on-failure

    network_mode: host
    ports:
      - 8840:8840

    volumes:
      - ./data:/data/WatchYourLAN

    environment:
      IFACES: "wlan0 eth0"
      TZ: America/Los_Angeles
