# https://github.com/dgtlmoon/changedetection.io/blob/master/docker-compose.yml

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    restart: on-failure

    ports:
      - 5000:5000

    depends_on:
      - caddy-docker-proxy
    labels:
      caddy: changedetection.airmac.local
      caddy.reverse_proxy: "{{upstreams 5000}}"
      caddy.tls: internal
    networks:
      - caddy

    volumes:
      - changedetection_data:/datastore

volumes:
  changedetection_data:
