# https://github.com/linuxserver/docker-syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    restart: on-failure

    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    networks:
      - caddy
    labels:
      caddy: syncthing.pibox.lan
      caddy.reverse_proxy: "{{ upstreams http 8384 }}"

    volumes:
      - ./config:/config
      - ./data:/data

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
