# https://github.com/homebridge/docker-homebridge
#
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: on-failure
    hostname: homebridge
    container_name: homebridge

    network_mode: host
    # networks:
    #   - caddy
    # ports:
    #   - 8581:8581
    #   - 9557:9557 # Alexa
    #   - 35219:35219 # Zigbee2MQTT HAP (bridge)
    #   - 51714:51714 # Homebridge HAP (bridge)
    #   - 46768:46768 # Alexa HAP (bridge)

    volumes:
      - ./config:/homebridge
      # - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    environment:
      - ENABLE_AVAHI=0 # Optional: Enable/disable Avahi (1=enabled, 0=disabled)

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8581 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
