services:
  # https://tailscale.com/docs/features/containers/docker/how-to/connect-docker-container
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: tailscale
    restart: on-failure

    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ./data/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN

    # networks:
    #   - caddy
    # labels:
    #   caddy: tailscale.pibox.lan
    #   caddy.reverse_proxy:  "{{upstreams https 8443}}"
    #   caddy.tls: internal

    env_file: .env

  # https://almeidapaulopt.github.io/tsdproxy/docs/docker/
  # https://github.com/almeidapaulopt/tsdproxy/blob/main/docker-compose.yaml
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    hostname: tsdproxy
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - tsdproxy_data:/data
      - ./config:/config

    env_file: .env
    depends_on:
      - tailscale

volumes:
  tsdproxy_data:
