# https://forgejo.org/docs/latest/admin/installation/docker/
services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:16
    container_name: forgejo
    hostname: forgejo
    restart: no
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      docktail.service.enable: true
      docktail.service.name: forgejo
      docktail.service.description: Git server
      docktail.service.port: 3000
      docktail.service.service-port: 443
      docktail.service.1.enable: true
      docktail.service.1.name: forgejo
      docktail.service.1.port: 2222
      docktail.service.1.protocol: tcp
      docktail.service.1.service-port: 22
    # ports:
    #   - 3000:3000
    #   - 222:22
