name: pibox

include:
  # Reverse Proxy
  # - ./services/caddy-docker-proxy/docker-compose.caddy-docker-proxy.yml
  # - ./services/nginx-proxy-manager/docker-compose.nginx-proxy-manager.yml

  # Pibox Home Page - upstreams 80
  # - ./services/homepage/docker-compose.homepage.yml
  # - ./services/homarr/docker-compose.homarr.yml
  # - ./services/cockpit-proxy/docker-compose.cockpit-proxy.yml

  # Pi-hole - upstreams 8080/9443
  - ./services/pihole/docker-compose.pihole.yml

  # ZigBee - upstreams 8081
  - ./services/mqtt/docker-compose.mqtt.yml
  - ./services/zigbee2mqtt/docker-compose.zigbee2mqtt.yml

  # Homebridge - upstreams 8581
  - ./services/homebridge/docker-compose.homebridge.yml

  # Jellyfin - upstreams 8096
  - ./services/jellyfin/docker-compose.jellyfin.yml

  # Conduit/Mautrix - upstreams 8448 and 8009 for web
  - ./services/conduit/docker-compose.conduit.yml

  # Ntfy - upstreams 8086
  # - ./services/ntfy/docker-compose.ntfy.yml

  # TODO
  # - ./services/tailscale/docker-compose.tailscale.yml
  # - ./services/changedetection/docker-compose.changedetection.yml
  # - ./services/syncthing/docker-compose.syncthing.yml

networks:
  caddy:
    external: true
