name: pibox

include:
  - ./services/pihole/pihole.docker-compose.yml
  - ./services/zigbee2mqtt/zigbee2mqtt.docker-compose.yml
  - ./services/caddy-docker-proxy/caddy-docker-proxy.docker-compose.yml
  # - ./services/homebridge/homebridge.docker-compose.yml

  # - ./services/ntfy/ntfy.docker-compose.yml
  # - ./services/changedetection/changedetection.docker-compose.yml
  # - ./services/jellyfin/jellyfin.docker-compose.yml
  # - ./services/syncthing/syncthing.docker-compose.yml
