# https://jellyfin.org/docs/general/installation/container/

services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: jellyfin/jellyfin
    restart: on-failure

    # Optional - specify the uid and gid you would like Jellyfin to use instead of root
    user: 1000:1000

    ports:
      - 8096:8096/tcp
      - 7359:7359/udp

    labels:
      caddy: jellyfin.pibox.lan
      caddy.reverse_proxy: "{{upstreams 8096}}"
      caddy.tls: internal

    networks:
      - caddy

    volumes:
      - ./config:/config
      - ./cache:/cache
      - /data/media:/media:ro

    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
