services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    ports:
      - 8085:8080

    networks:
      - caddy
    labels:
      caddy: glance.pibox.glance
      caddy.reverse_prozy: "{{upstreams http 8085}}"
      caddy.tls: internal
