services:
  cockpit-proxy:
    container_name: cockpit-proxy
    image: alpine
    restart: on-failure

    command: sh -c "sleep infinity"

    ports:
      - 80:9090

    networks:
      - caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"

    labels:
      caddy: cockpit.pibox.lan
      caddy.reverse_proxy: host.docker.internal:9090
      caddy.tls: internal
