services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    hostname: mqtt
    restart: no
    ports:
      - 1883:1883 # MQTT
      - 9001:9001 # HTTP/WebSockets
    volumes:
      - ./mosquitto:/mosquitto/config
