# https://homarr.dev/docs/getting-started/installation/docker/
# https://homarr.dev/docs/advanced/environment-variables/
services:
  homarr:
    hostname: homarr
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: on-failure

    environment:
      - SECRET_ENCRYPTION_KEY=f28c02ebf74dd69f167e3dbca7ea96c9fb6671bc5d698b8df80360e835d8e2d7

    networks:
      - caddy

    ports:
      - 80:7575
      - 8181:3000 # HTTP
      - 8182:3001 # Websockets

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/appdata
