services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    hostname: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped

    # rootless
    group_add:
      - dialout
    user: 1000:1000

    depends_on:
      - mqtt

    labels:
      caddy: zigbee2mqtt.pibox.lan
      caddy.reverse_proxy: "{{upstreams 8081}}"
      caddy.tls: "internal"

    networks:
      - caddy

    ports:
      - 8081:8080

    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro

    environment:
      - TZ=America/Los_Angeles

    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_3a7de9d2f912ec11942420c7bd930c07-if00-port0:/dev/ttyUSB0
