services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      PUID: 1000
      PGID: 1000
      PIHOLE_UID: 1000
      PIHOLE_GID: 1000
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - SYS_NICE
      - SYS_TIME
    ports:
      - 53:53/tcp # DNS
      - 53:53/udp # DNS
      # - 80:80/tcp # HTTP
      # - 443:443/tcp # HTTPS
      # - 67:67/udp # DHCP
      # - 123:123/udp # NTP
    labels:
      docktail.service.enable: true
      docktail.service.name: pihole
      docktail.service.description: Network-wide ad blocker
      docktail.service.port: 80
      docktail.service.service-port: 443
      docktail.service.1.enable: true
      docktail.service.1.name: pihole
      docktail.service.1.port: 53
      docktail.service.1.protocol: tcp
      docktail.service.1.service-port: 53
      docktail.service.network: ipv6net
    healthcheck:
      test: ["CMD", "pgrep", "-f", "pihole-FTL"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure:3
    networks:
      - ipv6net

networks:
  ipv6net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
