services:
  pihole:
    image: ${IMAGE_URL}
    container_name: ${SERVICE}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ./pihole.toml:/etc/pihole/pihole.toml
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - SYS_NICE
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
      - 443:443/tcp
      #- 67:67/udp # DHCP
      #- 123:123/udp # NTP
    labels:
      tsdproxy.enable: true
      tsdproxy.name: pihole
      tsdproxy.port.1: "443/https:443/https"
      tsdproxy.port.2: "80/http:80/http"
      tsdproxy.port.3: "53/tcp:53/tcp"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "pihole-FTL"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: on-failure:3
