# https://github.com/pi-hole/docker-pi-hole/
# https://docs.pi-hole.net/docker/configuration/
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    restart: on-failure

    # user: 1000:1000

    networks:
      - caddy
    labels:
      caddy: pihole.pibox.lan
      caddy.reverse_proxy: "{{upstreams https 8443}}"
      caddy.tls: internal

    volumes:
      - ./data:/etc/pihole
      - /etc/localtime:/etc/localtime:ro

    ports:
      - 53:53/tcp # DNS
      - 53:53/udp # DNS
      - 8080:8080/tcp # HTTP
      - 8443:8443/tcp # HTTPS

    environment:
      PIHOLE_UID: 1000
      PIHOLE_GUID: 1000
      TZ: America/Los_Angeles
      FTLCONF_dns_hosts: |-
        192.168.1.168 pibox.lan
        192.168.1.168 pibox.internal
      FTLCONF_ntp_sync_interval: 0
      FTLCONF_webserver_port: "8080,8443os,[::]:8080,[::]:8443os"
      FTLCONF_webserver_api_password: "correct horse battery staple"
      FTLCONF_misc_extraLogging: true
      FTLCONF_misc_dnsmasq_lines: |-
        address=/pibox.lan/192.168.1.168
        address=/pibox.internal/192.168.1.168
      FTLCONF_dns_listeningMode: LOCAL
      FTLCONF_dns_upstreams: |-
        1.1.1.1
        1.0.0.1
        8.8.8.8
        8.8.4.4

    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      - SYS_NICE
