# https://github.com/aceberg/WatchYourPorts
services:
  watchyourports:
    image: aceberg/watchyourports
    container_name: watchyourports
    hostname: watchyourports
    restart: on-failure

    volumes:
      - ./data:/data/WatchYourPorts

    environment:
      TZ: America/Los_Angeles # required, default: ""
      HOST: "0.0.0.0" # optional, default: 0.0.0.0
      PORT: "8853" # optional, default: 8853
      THEME: "grass" # optional, default: grass
      COLOR: "dark" # optional, default: dark
